[project]
id = "ambient_test_project"
name = "ambient-test-project"
version = "0.0.1"

[components]
player_camera_ref = { type = "EntityId", name = "Player camera ref", description = "", attributes = [
    "Debuggable",
] }
player_mesh_ref = { type = "EntityId", name = "Player mesh ref", description = "", attributes = [
    "Debuggable",
] }
player_target_ref = { type = "EntityId", name = "Player target ref", description = "", attributes = [
    "Debuggable",
] }
player_target_rotation = { type = "Quat", name = "Player target quat", description = "", attributes = [
    "Debuggable",
] }
player_target_vec = { type = "Vec3", name = "Player target vector", description = "", attributes = [
    "Debuggable",
] }
