[project]
id = "ambient_test_project"
name = "ambient-test-project"
version = "0.0.1"

[components]
player_camera_ref = { type = "EntityId", name = "Player camera ref", description = "", attributes = [
    "Debuggable",
] }
camera_pitch = { type = "F32", name = "Camera pitch", description = "camera rotation pitch" }
