[project]
id = "ambient_test_project"
name = "ambient-test-project"
version = "0.0.1"

[components]
player_camera_ref = { type = "EntityId", name = "Player camera ref", description = "", attributes = [
    "Debuggable",
] }
player_mesh_ref = { type = "EntityId", name = "Player mesh ref", description = "", attributes = [
    "Debuggable",
] }
view_vertical_rotation = { type = "Quat", name = "Vertical Rotation", description = "Vertical rotation quat for player", attributes=["Networked"]}
player_mouse_delta_x = { type = "F32", name = "Player Mouse delta X", description = "The mouse delta X." }
player_mouse_delta_y = { type = "F32", name = "Player Mouse delta Y", description = "The mouse delta Y." }
player_input_direction = { type = "Vec2", name = "Direction", description = "The movement direction of the player." }
player_vertical_rotation_angle = { type = "F32", name = "Player vertical rotation angle", description = "Player vertical rotation angle for caping camera", attributes=["Networked"] }

player_text_ref = { type = "EntityId", name = "Player Text Reference", description = "EntityId of a player's text" }
player_text_container_ref = { type = "EntityId", name = "Player Text Container Reference", description = "EntityId of a player's text container" }

[messages.input]
name = "Player Input"
description = "Describes the input state of the player."
[messages.input.fields]
input_direction = { type = "Vec2", name = "Direction", description = "The movement direction of the player." }
mouse_delta_x = { type = "F32", name = "Mouse delta X", description = "The mouse delta X." }
mouse_delta_y = { type = "F32", name = "Mouse delta Y", description = "The mouse delta Y." }
